language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test polls

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "us-west-2"  
  app: "swe1"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-198031710711"
  on:
    branch: main