language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite_swe1_app,polls manage.py test

after_script:
  - coveralls